# Parameters for apriltag detector node
family: "tag36h11"
ndetectors: 1
nthreads: 3
quad_decimate: 2.0
quad_sigma: 0.0
refine_edges: 1
decode_sharpening: 0.25
tag_size: 0.065
detection_freq: -1
rectify_alpha: 0.0