// Generated by gencpp from file duckietown_msgs/DiagnosticsRosTopicArray.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_DIAGNOSTICSROSTOPICARRAY_H
#define DUCKIETOWN_MSGS_MESSAGE_DIAGNOSTICSROSTOPICARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <duckietown_msgs/DiagnosticsRosTopic.h>

namespace duckietown_msgs
{
template <class ContainerAllocator>
struct DiagnosticsRosTopicArray_
{
  typedef DiagnosticsRosTopicArray_<ContainerAllocator> Type;

  DiagnosticsRosTopicArray_()
    : header()
    , topics()  {
    }
  DiagnosticsRosTopicArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , topics(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::duckietown_msgs::DiagnosticsRosTopic_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::duckietown_msgs::DiagnosticsRosTopic_<ContainerAllocator> >> _topics_type;
  _topics_type topics;





  typedef boost::shared_ptr< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> const> ConstPtr;

}; // struct DiagnosticsRosTopicArray_

typedef ::duckietown_msgs::DiagnosticsRosTopicArray_<std::allocator<void> > DiagnosticsRosTopicArray;

typedef boost::shared_ptr< ::duckietown_msgs::DiagnosticsRosTopicArray > DiagnosticsRosTopicArrayPtr;
typedef boost::shared_ptr< ::duckietown_msgs::DiagnosticsRosTopicArray const> DiagnosticsRosTopicArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator1> & lhs, const ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.topics == rhs.topics;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator1> & lhs, const ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75d6b38d91572d9e365e9ae3cf66db75";
  }

  static const char* value(const ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75d6b38d91572d9eULL;
  static const uint64_t static_value2 = 0x365e9ae3cf66db75ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/DiagnosticsRosTopicArray";
  }

  static const char* value(const ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"duckietown_msgs/DiagnosticsRosTopic[] topics\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: duckietown_msgs/DiagnosticsRosTopic\n"
"# Topic direction (this has to match duckietown.TopicDirection)\n"
"uint8 TOPIC_DIRECTION_INBOUND = 0\n"
"uint8 TOPIC_DIRECTION_OUTBOUND = 1\n"
"\n"
"# Topic type (this has to match duckietown.TopicType)\n"
"uint8 TOPIC_TYPE_GENERIC = 0\n"
"uint8 TOPIC_TYPE_DRIVER = 1\n"
"uint8 TOPIC_TYPE_PERCEPTION = 2\n"
"uint8 TOPIC_TYPE_CONTROL = 3\n"
"uint8 TOPIC_TYPE_PLANNING = 4\n"
"uint8 TOPIC_TYPE_LOCALIZATION = 5\n"
"uint8 TOPIC_TYPE_MAPPING = 6\n"
"uint8 TOPIC_TYPE_SWARM = 7\n"
"uint8 TOPIC_TYPE_BEHAVIOR = 8\n"
"uint8 TOPIC_TYPE_VISUALIZATION = 9\n"
"uint8 TOPIC_TYPE_INFRASTRUCTURE = 10\n"
"uint8 TOPIC_TYPE_COMMUNICATION = 11\n"
"uint8 TOPIC_TYPE_DIAGNOSTICS = 12\n"
"uint8 TOPIC_TYPE_DEBUG = 20\n"
"\n"
"string node                     # Node publishing this message\n"
"string name                     # Topic object of the diagnostics\n"
"string help                     # Topic description\n"
"uint8 type                      # Topic type\n"
"uint8 direction                 # Topic direction\n"
"float32 frequency               # Topic frequency (Hz)\n"
"float32 effective_frequency     # Topic (effective) frequency (Hz)\n"
"float32 healthy_frequency       # Frequency at which this topic can be considered healthy\n"
"float32 bandwidth               # Topic bandwidth (byte/s)\n"
"bool enabled                    # Topic switch\n"
;
  }

  static const char* value(const ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.topics);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DiagnosticsRosTopicArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::DiagnosticsRosTopicArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "topics[]" << std::endl;
    for (size_t i = 0; i < v.topics.size(); ++i)
    {
      s << indent << "  topics[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::duckietown_msgs::DiagnosticsRosTopic_<ContainerAllocator> >::stream(s, indent + "    ", v.topics[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_DIAGNOSTICSROSTOPICARRAY_H
