// Generated by gencpp from file duckietown_msgs/DuckiebotLED.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_DUCKIEBOTLED_H
#define DUCKIETOWN_MSGS_MESSAGE_DUCKIEBOTLED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/ColorRGBA.h>

namespace duckietown_msgs
{
template <class ContainerAllocator>
struct DuckiebotLED_
{
  typedef DuckiebotLED_<ContainerAllocator> Type;

  DuckiebotLED_()
    : header()
    , colors()  {
    }
  DuckiebotLED_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , colors(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::std_msgs::ColorRGBA_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::std_msgs::ColorRGBA_<ContainerAllocator> >> _colors_type;
  _colors_type colors;





  typedef boost::shared_ptr< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> const> ConstPtr;

}; // struct DuckiebotLED_

typedef ::duckietown_msgs::DuckiebotLED_<std::allocator<void> > DuckiebotLED;

typedef boost::shared_ptr< ::duckietown_msgs::DuckiebotLED > DuckiebotLEDPtr;
typedef boost::shared_ptr< ::duckietown_msgs::DuckiebotLED const> DuckiebotLEDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duckietown_msgs::DuckiebotLED_<ContainerAllocator1> & lhs, const ::duckietown_msgs::DuckiebotLED_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.colors == rhs.colors;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duckietown_msgs::DuckiebotLED_<ContainerAllocator1> & lhs, const ::duckietown_msgs::DuckiebotLED_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1a05ea07d5c98d935c3a53fe6500186";
  }

  static const char* value(const ::duckietown_msgs::DuckiebotLED_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1a05ea07d5c98d9ULL;
  static const uint64_t static_value2 = 0x35c3a53fe6500186ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/DuckiebotLED";
  }

  static const char* value(const ::duckietown_msgs::DuckiebotLED_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"std_msgs/ColorRGBA[] colors\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/ColorRGBA\n"
"float32 r\n"
"float32 g\n"
"float32 b\n"
"float32 a\n"
;
  }

  static const char* value(const ::duckietown_msgs::DuckiebotLED_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.colors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DuckiebotLED_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::DuckiebotLED_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::DuckiebotLED_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "colors[]" << std::endl;
    for (size_t i = 0; i < v.colors.size(); ++i)
    {
      s << indent << "  colors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "    ", v.colors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_DUCKIEBOTLED_H
