// Generated by gencpp from file duckietown_msgs/EncoderStamped.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_ENCODERSTAMPED_H
#define DUCKIETOWN_MSGS_MESSAGE_ENCODERSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace duckietown_msgs
{
template <class ContainerAllocator>
struct EncoderStamped_
{
  typedef EncoderStamped_<ContainerAllocator> Type;

  EncoderStamped_()
    : header()
    , vel_encoder(0.0)
    , count(0)  {
    }
  EncoderStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vel_encoder(0.0)
    , count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _vel_encoder_type;
  _vel_encoder_type vel_encoder;

   typedef int64_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> const> ConstPtr;

}; // struct EncoderStamped_

typedef ::duckietown_msgs::EncoderStamped_<std::allocator<void> > EncoderStamped;

typedef boost::shared_ptr< ::duckietown_msgs::EncoderStamped > EncoderStampedPtr;
typedef boost::shared_ptr< ::duckietown_msgs::EncoderStamped const> EncoderStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::EncoderStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duckietown_msgs::EncoderStamped_<ContainerAllocator1> & lhs, const ::duckietown_msgs::EncoderStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vel_encoder == rhs.vel_encoder &&
    lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duckietown_msgs::EncoderStamped_<ContainerAllocator1> & lhs, const ::duckietown_msgs::EncoderStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bceed13d0df81fff9a99f0c6a78e8f33";
  }

  static const char* value(const ::duckietown_msgs::EncoderStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbceed13d0df81fffULL;
  static const uint64_t static_value2 = 0x9a99f0c6a78e8f33ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/EncoderStamped";
  }

  static const char* value(const ::duckietown_msgs::EncoderStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 vel_encoder\n"
"int64 count\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::duckietown_msgs::EncoderStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vel_encoder);
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncoderStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::EncoderStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::EncoderStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vel_encoder: ";
    Printer<float>::stream(s, indent + "  ", v.vel_encoder);
    s << indent << "count: ";
    Printer<int64_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_ENCODERSTAMPED_H
