// Generated by gencpp from file duckietown_msgs/EpisodeStart.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_EPISODESTART_H
#define DUCKIETOWN_MSGS_MESSAGE_EPISODESTART_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace duckietown_msgs
{
template <class ContainerAllocator>
struct EpisodeStart_
{
  typedef EpisodeStart_<ContainerAllocator> Type;

  EpisodeStart_()
    : header()
    , episode_name()
    , other_payload_yaml()  {
    }
  EpisodeStart_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , episode_name(_alloc)
    , other_payload_yaml(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _episode_name_type;
  _episode_name_type episode_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _other_payload_yaml_type;
  _other_payload_yaml_type other_payload_yaml;





  typedef boost::shared_ptr< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> const> ConstPtr;

}; // struct EpisodeStart_

typedef ::duckietown_msgs::EpisodeStart_<std::allocator<void> > EpisodeStart;

typedef boost::shared_ptr< ::duckietown_msgs::EpisodeStart > EpisodeStartPtr;
typedef boost::shared_ptr< ::duckietown_msgs::EpisodeStart const> EpisodeStartConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::EpisodeStart_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duckietown_msgs::EpisodeStart_<ContainerAllocator1> & lhs, const ::duckietown_msgs::EpisodeStart_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.episode_name == rhs.episode_name &&
    lhs.other_payload_yaml == rhs.other_payload_yaml;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duckietown_msgs::EpisodeStart_<ContainerAllocator1> & lhs, const ::duckietown_msgs::EpisodeStart_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9c9ddf1cb6334de0336392fe315bfa9";
  }

  static const char* value(const ::duckietown_msgs::EpisodeStart_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9c9ddf1cb6334deULL;
  static const uint64_t static_value2 = 0x0336392fe315bfa9ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/EpisodeStart";
  }

  static const char* value(const ::duckietown_msgs::EpisodeStart_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string episode_name\n"
"string other_payload_yaml\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::duckietown_msgs::EpisodeStart_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.episode_name);
      stream.next(m.other_payload_yaml);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EpisodeStart_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::EpisodeStart_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::EpisodeStart_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "episode_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.episode_name);
    s << indent << "other_payload_yaml: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.other_payload_yaml);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_EPISODESTART_H
