// Generated by gencpp from file duckietown_msgs/LFstatus.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_LFSTATUS_H
#define DUCKIETOWN_MSGS_MESSAGE_LFSTATUS_H

#include <ros/service_traits.h>


#include <duckietown_msgs/LFstatusRequest.h>
#include <duckietown_msgs/LFstatusResponse.h>


namespace duckietown_msgs
{

struct LFstatus
{

typedef LFstatusRequest Request;
typedef LFstatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LFstatus
} // namespace duckietown_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::duckietown_msgs::LFstatus > {
  static const char* value()
  {
    return "b59a0adbfa1b994feb973fdc4fcbe6db";
  }

  static const char* value(const ::duckietown_msgs::LFstatus&) { return value(); }
};

template<>
struct DataType< ::duckietown_msgs::LFstatus > {
  static const char* value()
  {
    return "duckietown_msgs/LFstatus";
  }

  static const char* value(const ::duckietown_msgs::LFstatus&) { return value(); }
};


// service_traits::MD5Sum< ::duckietown_msgs::LFstatusRequest> should match
// service_traits::MD5Sum< ::duckietown_msgs::LFstatus >
template<>
struct MD5Sum< ::duckietown_msgs::LFstatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::duckietown_msgs::LFstatus >::value();
  }
  static const char* value(const ::duckietown_msgs::LFstatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::duckietown_msgs::LFstatusRequest> should match
// service_traits::DataType< ::duckietown_msgs::LFstatus >
template<>
struct DataType< ::duckietown_msgs::LFstatusRequest>
{
  static const char* value()
  {
    return DataType< ::duckietown_msgs::LFstatus >::value();
  }
  static const char* value(const ::duckietown_msgs::LFstatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::duckietown_msgs::LFstatusResponse> should match
// service_traits::MD5Sum< ::duckietown_msgs::LFstatus >
template<>
struct MD5Sum< ::duckietown_msgs::LFstatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::duckietown_msgs::LFstatus >::value();
  }
  static const char* value(const ::duckietown_msgs::LFstatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::duckietown_msgs::LFstatusResponse> should match
// service_traits::DataType< ::duckietown_msgs::LFstatus >
template<>
struct DataType< ::duckietown_msgs::LFstatusResponse>
{
  static const char* value()
  {
    return DataType< ::duckietown_msgs::LFstatus >::value();
  }
  static const char* value(const ::duckietown_msgs::LFstatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_LFSTATUS_H
