// Generated by gencpp from file duckietown_msgs/LightSensor.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_LIGHTSENSOR_H
#define DUCKIETOWN_MSGS_MESSAGE_LIGHTSENSOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace duckietown_msgs
{
template <class ContainerAllocator>
struct LightSensor_
{
  typedef LightSensor_<ContainerAllocator> Type;

  LightSensor_()
    : header()
    , r(0)
    , g(0)
    , b(0)
    , c(0)
    , real_lux(0)
    , lux(0)
    , temp(0)  {
    }
  LightSensor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , r(0)
    , g(0)
    , b(0)
    , c(0)
    , real_lux(0)
    , lux(0)
    , temp(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _r_type;
  _r_type r;

   typedef int32_t _g_type;
  _g_type g;

   typedef int32_t _b_type;
  _b_type b;

   typedef int32_t _c_type;
  _c_type c;

   typedef int32_t _real_lux_type;
  _real_lux_type real_lux;

   typedef int32_t _lux_type;
  _lux_type lux;

   typedef int32_t _temp_type;
  _temp_type temp;





  typedef boost::shared_ptr< ::duckietown_msgs::LightSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::LightSensor_<ContainerAllocator> const> ConstPtr;

}; // struct LightSensor_

typedef ::duckietown_msgs::LightSensor_<std::allocator<void> > LightSensor;

typedef boost::shared_ptr< ::duckietown_msgs::LightSensor > LightSensorPtr;
typedef boost::shared_ptr< ::duckietown_msgs::LightSensor const> LightSensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::LightSensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::LightSensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duckietown_msgs::LightSensor_<ContainerAllocator1> & lhs, const ::duckietown_msgs::LightSensor_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.r == rhs.r &&
    lhs.g == rhs.g &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.real_lux == rhs.real_lux &&
    lhs.lux == rhs.lux &&
    lhs.temp == rhs.temp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duckietown_msgs::LightSensor_<ContainerAllocator1> & lhs, const ::duckietown_msgs::LightSensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::LightSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::LightSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::LightSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::LightSensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::LightSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::LightSensor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::LightSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d3098cdc59f2c0a8f7c461ef10ca781";
  }

  static const char* value(const ::duckietown_msgs::LightSensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d3098cdc59f2c0aULL;
  static const uint64_t static_value2 = 0x8f7c461ef10ca781ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::LightSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/LightSensor";
  }

  static const char* value(const ::duckietown_msgs::LightSensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::LightSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 r\n"
"int32 g\n"
"int32 b\n"
"int32 c\n"
"int32 real_lux\n"
"int32 lux\n"
"int32 temp\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::duckietown_msgs::LightSensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::LightSensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.real_lux);
      stream.next(m.lux);
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightSensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::LightSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::LightSensor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "r: ";
    Printer<int32_t>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<int32_t>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<int32_t>::stream(s, indent + "  ", v.c);
    s << indent << "real_lux: ";
    Printer<int32_t>::stream(s, indent + "  ", v.real_lux);
    s << indent << "lux: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lux);
    s << indent << "temp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_LIGHTSENSOR_H
