// Generated by gencpp from file duckietown_msgs/NodeRequestParamsUpdate.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_NODEREQUESTPARAMSUPDATE_H
#define DUCKIETOWN_MSGS_MESSAGE_NODEREQUESTPARAMSUPDATE_H

#include <ros/service_traits.h>


#include <duckietown_msgs/NodeRequestParamsUpdateRequest.h>
#include <duckietown_msgs/NodeRequestParamsUpdateResponse.h>


namespace duckietown_msgs
{

struct NodeRequestParamsUpdate
{

typedef NodeRequestParamsUpdateRequest Request;
typedef NodeRequestParamsUpdateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NodeRequestParamsUpdate
} // namespace duckietown_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::duckietown_msgs::NodeRequestParamsUpdate > {
  static const char* value()
  {
    return "e8496433f08c35370e7779defca9aa19";
  }

  static const char* value(const ::duckietown_msgs::NodeRequestParamsUpdate&) { return value(); }
};

template<>
struct DataType< ::duckietown_msgs::NodeRequestParamsUpdate > {
  static const char* value()
  {
    return "duckietown_msgs/NodeRequestParamsUpdate";
  }

  static const char* value(const ::duckietown_msgs::NodeRequestParamsUpdate&) { return value(); }
};


// service_traits::MD5Sum< ::duckietown_msgs::NodeRequestParamsUpdateRequest> should match
// service_traits::MD5Sum< ::duckietown_msgs::NodeRequestParamsUpdate >
template<>
struct MD5Sum< ::duckietown_msgs::NodeRequestParamsUpdateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::duckietown_msgs::NodeRequestParamsUpdate >::value();
  }
  static const char* value(const ::duckietown_msgs::NodeRequestParamsUpdateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::duckietown_msgs::NodeRequestParamsUpdateRequest> should match
// service_traits::DataType< ::duckietown_msgs::NodeRequestParamsUpdate >
template<>
struct DataType< ::duckietown_msgs::NodeRequestParamsUpdateRequest>
{
  static const char* value()
  {
    return DataType< ::duckietown_msgs::NodeRequestParamsUpdate >::value();
  }
  static const char* value(const ::duckietown_msgs::NodeRequestParamsUpdateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::duckietown_msgs::NodeRequestParamsUpdateResponse> should match
// service_traits::MD5Sum< ::duckietown_msgs::NodeRequestParamsUpdate >
template<>
struct MD5Sum< ::duckietown_msgs::NodeRequestParamsUpdateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::duckietown_msgs::NodeRequestParamsUpdate >::value();
  }
  static const char* value(const ::duckietown_msgs::NodeRequestParamsUpdateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::duckietown_msgs::NodeRequestParamsUpdateResponse> should match
// service_traits::DataType< ::duckietown_msgs::NodeRequestParamsUpdate >
template<>
struct DataType< ::duckietown_msgs::NodeRequestParamsUpdateResponse>
{
  static const char* value()
  {
    return DataType< ::duckietown_msgs::NodeRequestParamsUpdate >::value();
  }
  static const char* value(const ::duckietown_msgs::NodeRequestParamsUpdateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_NODEREQUESTPARAMSUPDATE_H
