// Generated by gencpp from file duckietown_msgs/ObstacleType.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_OBSTACLETYPE_H
#define DUCKIETOWN_MSGS_MESSAGE_OBSTACLETYPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duckietown_msgs
{
template <class ContainerAllocator>
struct ObstacleType_
{
  typedef ObstacleType_<ContainerAllocator> Type;

  ObstacleType_()
    : type(0)  {
    }
  ObstacleType_(const ContainerAllocator& _alloc)
    : type(0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(DUCKIE)
  #undef DUCKIE
#endif
#if defined(_WIN32) && defined(CONE)
  #undef CONE
#endif

  enum {
    DUCKIE = 0u,
    CONE = 1u,
  };


  typedef boost::shared_ptr< ::duckietown_msgs::ObstacleType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::ObstacleType_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleType_

typedef ::duckietown_msgs::ObstacleType_<std::allocator<void> > ObstacleType;

typedef boost::shared_ptr< ::duckietown_msgs::ObstacleType > ObstacleTypePtr;
typedef boost::shared_ptr< ::duckietown_msgs::ObstacleType const> ObstacleTypeConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::ObstacleType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::ObstacleType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duckietown_msgs::ObstacleType_<ContainerAllocator1> & lhs, const ::duckietown_msgs::ObstacleType_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duckietown_msgs::ObstacleType_<ContainerAllocator1> & lhs, const ::duckietown_msgs::ObstacleType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::ObstacleType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::ObstacleType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::ObstacleType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::ObstacleType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::ObstacleType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::ObstacleType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::ObstacleType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ebfbd5f069d46cb29c52358b5e953fb";
  }

  static const char* value(const ::duckietown_msgs::ObstacleType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ebfbd5f069d46cbULL;
  static const uint64_t static_value2 = 0x29c52358b5e953fbULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::ObstacleType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/ObstacleType";
  }

  static const char* value(const ::duckietown_msgs::ObstacleType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::ObstacleType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 DUCKIE=0\n"
"uint8 CONE=1\n"
"uint8 type\n"
;
  }

  static const char* value(const ::duckietown_msgs::ObstacleType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::ObstacleType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::ObstacleType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::ObstacleType_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_OBSTACLETYPE_H
