// Generated by gencpp from file duckietown_msgs/SetValue.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_SETVALUE_H
#define DUCKIETOWN_MSGS_MESSAGE_SETVALUE_H

#include <ros/service_traits.h>


#include <duckietown_msgs/SetValueRequest.h>
#include <duckietown_msgs/SetValueResponse.h>


namespace duckietown_msgs
{

struct SetValue
{

typedef SetValueRequest Request;
typedef SetValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetValue
} // namespace duckietown_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::duckietown_msgs::SetValue > {
  static const char* value()
  {
    return "0aca93dcf6d857f0e5a0dc6be1eaa9fb";
  }

  static const char* value(const ::duckietown_msgs::SetValue&) { return value(); }
};

template<>
struct DataType< ::duckietown_msgs::SetValue > {
  static const char* value()
  {
    return "duckietown_msgs/SetValue";
  }

  static const char* value(const ::duckietown_msgs::SetValue&) { return value(); }
};


// service_traits::MD5Sum< ::duckietown_msgs::SetValueRequest> should match
// service_traits::MD5Sum< ::duckietown_msgs::SetValue >
template<>
struct MD5Sum< ::duckietown_msgs::SetValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::duckietown_msgs::SetValue >::value();
  }
  static const char* value(const ::duckietown_msgs::SetValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::duckietown_msgs::SetValueRequest> should match
// service_traits::DataType< ::duckietown_msgs::SetValue >
template<>
struct DataType< ::duckietown_msgs::SetValueRequest>
{
  static const char* value()
  {
    return DataType< ::duckietown_msgs::SetValue >::value();
  }
  static const char* value(const ::duckietown_msgs::SetValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::duckietown_msgs::SetValueResponse> should match
// service_traits::MD5Sum< ::duckietown_msgs::SetValue >
template<>
struct MD5Sum< ::duckietown_msgs::SetValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::duckietown_msgs::SetValue >::value();
  }
  static const char* value(const ::duckietown_msgs::SetValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::duckietown_msgs::SetValueResponse> should match
// service_traits::DataType< ::duckietown_msgs::SetValue >
template<>
struct DataType< ::duckietown_msgs::SetValueResponse>
{
  static const char* value()
  {
    return DataType< ::duckietown_msgs::SetValue >::value();
  }
  static const char* value(const ::duckietown_msgs::SetValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_SETVALUE_H
