// Generated by gencpp from file duckietown_msgs/ToFstatus.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_TOFSTATUS_H
#define DUCKIETOWN_MSGS_MESSAGE_TOFSTATUS_H

#include <ros/service_traits.h>


#include <duckietown_msgs/ToFstatusRequest.h>
#include <duckietown_msgs/ToFstatusResponse.h>


namespace duckietown_msgs
{

struct ToFstatus
{

typedef ToFstatusRequest Request;
typedef ToFstatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToFstatus
} // namespace duckietown_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::duckietown_msgs::ToFstatus > {
  static const char* value()
  {
    return "123f458c8760917a4db65e882cc7f43c";
  }

  static const char* value(const ::duckietown_msgs::ToFstatus&) { return value(); }
};

template<>
struct DataType< ::duckietown_msgs::ToFstatus > {
  static const char* value()
  {
    return "duckietown_msgs/ToFstatus";
  }

  static const char* value(const ::duckietown_msgs::ToFstatus&) { return value(); }
};


// service_traits::MD5Sum< ::duckietown_msgs::ToFstatusRequest> should match
// service_traits::MD5Sum< ::duckietown_msgs::ToFstatus >
template<>
struct MD5Sum< ::duckietown_msgs::ToFstatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::duckietown_msgs::ToFstatus >::value();
  }
  static const char* value(const ::duckietown_msgs::ToFstatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::duckietown_msgs::ToFstatusRequest> should match
// service_traits::DataType< ::duckietown_msgs::ToFstatus >
template<>
struct DataType< ::duckietown_msgs::ToFstatusRequest>
{
  static const char* value()
  {
    return DataType< ::duckietown_msgs::ToFstatus >::value();
  }
  static const char* value(const ::duckietown_msgs::ToFstatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::duckietown_msgs::ToFstatusResponse> should match
// service_traits::MD5Sum< ::duckietown_msgs::ToFstatus >
template<>
struct MD5Sum< ::duckietown_msgs::ToFstatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::duckietown_msgs::ToFstatus >::value();
  }
  static const char* value(const ::duckietown_msgs::ToFstatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::duckietown_msgs::ToFstatusResponse> should match
// service_traits::DataType< ::duckietown_msgs::ToFstatus >
template<>
struct DataType< ::duckietown_msgs::ToFstatusResponse>
{
  static const char* value()
  {
    return DataType< ::duckietown_msgs::ToFstatus >::value();
  }
  static const char* value(const ::duckietown_msgs::ToFstatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_TOFSTATUS_H
