description: >
    Lane filter for a curve left
constructor: lane_filter_generic.LaneFilterMoreGeneric
parameters:

    configuration:
        variables: !!omap
            - d:
                min: -0.15
                max: +0.3025
#                 resolution: 0.022
                resolution: 0.02 # like baseline

                units: m
                units_display: cm
                description: Distance from center lane

            - phi:
                min: -1.5
                max: +1.5125
                # resolution: 0.022
                resolution: 0.1 # like baseline

                units: rad
                units_display: deg
                description: Angle with respect to center lane

        localization_template: DT17_template_before_curve_left
        
        delta_segment: 0.05

        F: 1
        optimize: true
        bounds_theta_deg: null
        precision: float32
