events:
  at_stop_line:
    topic: "stop_line_filter_node/at_stop_line"
    msg_type: "BoolStamped"
    trigger: True
  # velocity_zero:
  #   topic: "lane_controller_node/car_cmd"
  #   msg_type: "Twist2DStamped"
  #   field: "v"
  #   trigger: 0.0
  joystick_override_on:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  parallel_autonomy_on:
    topic: "joy_mapper_node/parallel_autonomy"
    msg_type: "BoolStamped"
    trigger: True
    default: False
  parallel_autonomy_off:
    topic: "joy_mapper_node/parallel_autonomy"
    msg_type: "BoolStamped"
    trigger: False
    default: True
  intersection_go_implicit:
    topic: "implicit_intersection_go/intersection_go" #TODO check implicit_coordination_node topic and change to that
    msg_type: "BoolStamped"
    trigger: True
  intersection_go_explicit:
    topic: "coordinator_node/intersection_go"
    msg_type: "BoolStamped"
    trigger: True
  apriltag_parking:
    topic: "apriltag_postprocessing_node/apriltags_parking"
    msg_type: "BoolStamped"
    trigger: True
  parking_on:
    default: False
    topic: "parking_on"
    msg_type: "BoolStamped"
    trigger: True
  parking_off:
    default: True
    topic: "parking_on"
    msg_type: "BoolStamped"
    trigger: False

  joystick_override_off:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False
  deep_lane_following_on:
    default: False
    topic: "joy_mapper_node/deep_learn_toggle"
    msg_type: "BoolStamped"
    trigger: True
  deep_lane_following_off:
    default: True
    topic: "joy_mapper_node/deep_learn_toggle"
    msg_type: "BoolStamped"
    trigger: False

  charging_exit:
    default: False
    topic: "charging_control_node/ready_at_exit"
    msg_type: "BoolStamped"
    trigger: True

  ###### TO USE OPEN LOOP INTERSECTION CONTROL: (untested)
  # COMMENT OUT THE FIRST intersection_done, AND UNCOMMENT SECOND intersection_done
  intersection_done:  ## closed loop new
    topic: "intersection_navigation_node/intersection_done"
    msg_type: "BoolStamped"
    trigger: True
  # intersection_done: ## open loop old
  #   topic: "open_loop_intersection_control_node/intersection_done"
  #   msg_type: "BoolStamped"
  #   trigger: True

# TODO:
# - parking_on flag?

gates:
  at_stop_line_and_parking_off:
    gate_type: "AND"
    inputs:
      - at_stop_line
      - parking_off
    output_topic: "~at_stop_line_and_parking_off"
  at_stop_line_and_parking_on:
    gate_type: "AND"
    inputs:
      - at_stop_line
      - parking_on
    output_topic: "~at_stop_line_and_parking_on"
  joystick_override_on_and_parallel_autonomy_off:
    gate_type: AND
    inputs:
      - joystick_override_on
      - parallel_autonomy_off
    output_topic: "~joystick_override_on_and_parallel_autonomy_off"
  joystick_override_on_and_parallel_autonomy_on:
    gate_type: AND
    inputs:
      - joystick_override_on
      - parallel_autonomy_on
    output_topic: "~joystick_override_on_and_parallel_autonomy_on"
  intersection_go:
    gate_type: OR
    inputs:
      - intersection_go_implicit
      - intersection_go_explicit
    output_topic: "~intersection_go"
  joystick_override_off_and_deep_lane_on:
    gate_type: "AND"
    inputs:
      - joystick_override_off
      - deep_lane_following_on
    output_topic: "~joystick_override_off_and_deep_lane_on"
  joystick_override_off_and_deep_lane_off:
    gate_type: "AND"
    inputs:
      - joystick_override_off
      - deep_lane_following_off
    output_topic: "~joystick_override_off_and_deep_lane_off"
  intersection_done_and_deep_lane_off:
    gate_type: "AND"
    inputs:
      - intersection_done
      - deep_lane_following_off
    output_topic: "~intersection_done_and_deep_lane_off"
  intersection_done_and_deep_lane_on:
    gate_type: "AND"
    inputs:
      - intersection_done
      - deep_lane_following_on
    output_topic: "~intersection_done_and_deep_lane_on"

  at_stop_line_and_charging_exit:
    gate_type: "AND"
    inputs:
      - at_stop_line
      - charging_exit
    output_topic: "~at_stop_line_and_charging_exit"
