events:
  at_stop_line:
    topic: "stop_line_filter_node/at_stop_line"
    msg_type: "BoolStamped"
    trigger: True
  velocity_zero: 
    topic: "lane_controller_node/car_cmd"
    msg_type: "Twist2DStamped"
    field: "v"
    trigger: 0.0
  joystick_override_on: 
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  parallel_autonomy_on:
    topic: "joy_mapper_node/parallel_autonomy"
    msg_type: "BoolStamped"
    trigger: True
  parallel_autonomy_off:
    topic: "joy_mapper_node/parallel_autonomy"
    msg_type: "BoolStamped"
    trigger: False
  intersection_go_implicit:
    topic: "implicit_coord/flag_go_wait"
    msg_type: "BoolStamped"
    trigger: True
  intersection_go_explicit:
    topic: "LED_coordination/move_intersection"
    msg_type: "BoolStamped"
    trigger: True
  apriltag_parking:
    topic: "apriltag_postprocessing_node/apriltag_parking"
    msg_type: "BoolStamped"
    trigger: True
  parking_active:
    topic: "parking_active"
    msg_type: "BoolStamped"
    trigger: True

# TODO: 
# - parking_active flag?

gates:
  at_stop_line_and_velocity_zero:
    gate_type: "AND"
    inputs:
      - at_stop_line
      - velocity_zero
    output_topic: "~at_stop_line_and_velocity_zero"
  apriltag_parking_and_parking_active:
    gate_type: AND
    inputs:
      - apriltag_parking
      - parking_active
    output_topic: "~apriltag_parking_and_parking_active"
  joystick_override_on_and_parallel_autonomy_off:
    gate_type: AND
    inputs:
      - joystick_override_on
      - parallel_autonomy_off
    output_topic: "~joystick_override_on_and_parallel_autonomy_off"
  joystick_override_on_and_parallel_autonomy_on:
    gate_type: AND
    inputs:
      - joystick_override_on
      - parallel_autonomy_on
    output_topic: "~joystick_override_on_and_parallel_autonomy_on"
  intersection_go:
    gate_type: OR
    inputs:
      - intersection_go_implicit
      - intersection_go_explicit
    output_topic: "~intersection_go"
  intersection_done_and_parallel_autonomy_on:
    gate_type: "AND"
    inputs: 
      - intersection_done
      - parallel_autonomy_on
    output_topic: "~intersection_done_and_parallel_autonomy"
  intersection_done_and_parallel_autonomy_off:
    gate_type: "AND"
    inputs:
      - intersection_done
      - parallel_autonomy_off
    output_topic: "~intersection_done_and_not_parallel_autonomy"
