events:
  intersection_done:
    topic: "open_loop_intersection_control_node/intersection_done"
    trigger: True
  parallel_autonomy_on:
    topic: "joy_mapper_node/parallel_autonomy"
    trigger: True
  parallel_autonomy_off:
    topic: "joy_mapper_node/parallel_autonomy"
    trigger: False

gates:
  intersection_done_and_parallel_autonomy_on:
    gate_type: "AND"
    inputs: 
      - intersection_done
      - parallel_autonomy_on
    output_topic: "~intersection_done_and_parallel_autonomy"
  intersection_done_and_parallel_autonomy_off:
    gate_type: "AND"
    inputs:
      - intersection_done
      - parallel_autonomy_off
    output_topic: "~intersection_done_and_not_parallel_autonomy"
  at_stop_line_and_velocity_zero:
    gate_type: "AND"
    inputs:
      - at_stop_line
      - velocity_zero
      output_topic: "~at_stop_line_and_velocity_zero"