img_size: [120,160]
top_cutoff: 40

# should be an array of 2 elements. The first is the name of the class
# and the second should be the parameters. 
# The class should be an abstract instance of LineDetectorInterface
detector: 
  - line_detector.LineDetectorHSV
  - configuration:
        dilation_kernel_size: 3
        canny_thresholds: [50,150]
        hough_threshold: 20
        hough_min_line_length: 3
        hough_max_line_gap:    1

        hsv_white1:  [0,0,50]
        hsv_white2:  [180,120,255]
        hsv_yellow1: [25,210,50]
        hsv_yellow2: [45,255,255]
        hsv_red1:    [0,200,50]
        hsv_red2:    [15,255,255]
        hsv_red3:    [165,200,50]
        hsv_red4:    [180,255,255]
