description: Three way intersection
constructor: duckietown_segmaps.compose_maps
parameters:
  grid_spacing: 0.584
  tiles:
    - cell: [0, 0]
      name: DT17_tile_straight
      rotation: 0
    - cell: [1, 0]
      name: DT17_tile_three_way_center
      rotation: 0
    - cell: [1, 1]
      name: DT17_tile_straight
      rotation: -90
    - cell: [1, -1]
      name: DT17_tile_straight
      rotation: 90
