description: The center of a 3-way intersection
constructor: duckietown_segmaps.get_map_intersection_center
parameters:
  tile_size: 0.558 # outer white to outer white
  tile_spacing: 0.584
  width_yellow: 0.024
  width_white: 0.048
  width_red: 0.048
  num_roads: 3

#
# description: The center of a three-way intersection.
# constructor: duckietown_segmaps.three_way_intersection
# parameters:
#     tile_size: 0.558 # outer white to outer white
#     tile_spacing: 0.584
#     width_white: 0.048
