(cl:in-package duckietown_msgs-srv)
(cl:export '(SENSOR_POSITION-VAL
          SENSOR_POSITION
          ACCELERATION_X-VAL
          ACCELERATION_X
          ACCELERATION_Y-VAL
          ACCELERATION_Y
          ACCELERATION_Z-VAL
          ACCELERATION_Z
          TIMESTAMP_ACCELERATION-VAL
          TIMESTAMP_ACCELERATION
          GYRO_X-VAL
          GYRO_X
          GYRO_Y-VAL
          GYRO_Y
          GYRO_Z-VAL
          GYRO_Z
          TIMESTAMP_GYRO-VAL
          TIMESTAMP_GYRO
          MAGENTIC_FIELD_X-VAL
          MAGENTIC_FIELD_X
          MAGENTIC_FIELD_Y-VAL
          MAGENTIC_FIELD_Y
          MAGENTIC_FIELD_Z-VAL
          MAGENTIC_FIELD_Z
          TIMESTAMP_MAGNETIC_FIELD-VAL
          TIMESTAMP_MAGNETIC_FIELD
          TEMPERATURE-VAL
          TEMPERATURE
))