# default parameters for lane_filter/lane_filter_node
mean_d_0: 0
mean_phi_0: 0
sigma_d_0: 0.1
sigma_phi_0: 0.1
delta_d: 0.02
delta_phi: 0.05
d_max: 0.2
d_min: -0.2
phi_min: -0.7
phi_max: 0.7
cov_v: 0.5
linewidth_white: 0.05
linewidth_yellow: 0.03
lanewidth: 0.19
min_max: 0.3
