# parameters for deadreckoning_node

# How frequently to publish odometry
publish_hz: 10.0

# Max allowable age of last encoder message, after which
# linear and angular velocities are set to zero
encoder_stale_dt: 1.0

# Should be specified elsewhere
ticks_per_meter: 656

# Lateral distance between the center of the two wheels (in meters)
wheelbase: 0.1

# origin reference frame name
origin_frame: "~/odom"

# target reference frame name
target_frame: "~/base_footprint"

# Verbose output
debug: False