description: 3 by 3 loop
constructor: duckietown_segmaps.compose_maps
parameters:
  grid_spacing: 0.584
  tiles:
    - cell: [1, 0]
      name: DT17_tile_straight
      rotation: -90
    - cell: [1, -1]
      name: DT17_tile_curve_right
      rotation: -90
    - cell: [0, -1]
      name: DT17_tile_straight
      rotation: -180
    - cell: [-1, -1]
      name: DT17_tile_curve_right
      rotation: -180
    - cell: [-1, 0]
      name: DT17_tile_straight
      rotation: -270
    - cell: [-1, 1]
      name: DT17_tile_curve_right
      rotation: -270
    - cell: [0, 1]
      name: DT17_tile_straight
      rotation: 0
    - cell: [1, 1]
      name: DT17_tile_curve_right
      rotation: 0
    - cell: [0, 0]
      name: DT17_tile_empty
      rotation: 0
